### ISSUE TITLE
[BUG] unable to build OpenCE 1.5.0 with docker

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce-builder#109]
The following error is seen while building OpenCE 1.5.0 with docker:

```
HEAD is now at 841253d Release numactl 2.0.12
Traceback (most recent call last):
  File "/root/open_ce/build_feedstock.py", line 166, in build_feedstock_from_command
    conda_build.api.build(os.path.join(os.getcwd(), recipe['path']),
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2120, in build
    m.parse_until_resolved(allow_no_other_outputs=True)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 1061, in parse_until_resolved
    self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=allow_no_other_outputs,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 1001, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 1568, in _get_contents
    env.globals.update(environ.get_dict(m=self, skip_build_id=skip_build_id))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 282, in get_dict
    d.update(meta_vars(m, skip_build_id=skip_build_id))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 486, in meta_vars
    d.update(get_git_info(git_exe, git_dir, meta.config.debug))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 193, in get_git_info
    from conda._vendor.auxlib.packaging import _get_version_from_git_tag
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
[OPEN-CE-ERROR]-11 Unable to build recipe: numactl-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: numactl-feedstock
```

**Comment by cdeepali** [comment]
Conda released v4.11 today, which moves auxlib. 
The import for auxlib is fixed in conda-build v3.21.7 - https://github.com/conda/conda-build/pull/4335#issuecomment-989213445. 

We need to update our Dockerfiles to use conda-build v3.21.7.
