### ISSUE TITLE
[BUG] - conda-bld/work - file not found

### ISSUE THREAD

**Issue by ticlazau** [open-ce/open-ce-builder#120]
I am trying to compile the latest open-ce version and I am getting this error: 

conda-bld/work - file not found 

```
`HEAD is now at 8eb554c updated v1.5.8
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/florin/anaconda3/envs/opence/conda-bld/work' -> '/home/florin/anaconda3/envs/opence/conda-bld/fire_1651413312773/work'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/utils.py", line 384, in _run_helper
    return func(*args, **kwargs)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_tree.py", line 327, in _create_commands_helper
    retval = _create_commands(repo_dir,
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_tree.py", line 567, in _create_commands
    packages, version, run_deps, host_deps, build_deps, test_deps, output_files = _get_package_dependencies(
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_tree.py", line 130, in _get_package_dependencies
    metas = conda_utils.render_yaml(path, variants, variant_config_files)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/conda_utils.py", line 53, in render_yaml
    metas = conda_build.api.render(path,
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/api.py", line 42, in render
    metadata_tuples = render_recipe(recipe_path, bypass_env_check=bypass_env_check,
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/render.py", line 838, in render_recipe
    m.config.compute_build_id(m.name(), m.version(), reset=reset_build_id)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/config.py", line 611, in compute_build_id
    shutil.move(old_dir, work_dir)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/florin/anaconda3/envs/opence/conda-bld/work'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/florin/anaconda3/envs/opence/bin/open-ce", line 137, in <module>
    _main()
  File "/home/florin/anaconda3/envs/opence/bin/open-ce", line 133, in _main
    args.func(args)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_env.py", line 84, in build_env
    build_tree = construct_build_tree(args)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_tree.py", line 681, in construct_build_tree
    return BuildTree(env_config_files=args.env_config_file,
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_tree.py", line 202, in __init__
    variant_tree, external_deps, channels = self._create_nodes(variant)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_tree.py", line 314, in _create_nodes
    commands = utils.run_in_parallel(self._create_commands_helper, create_commands_args)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/utils.py", line 395, in run_in_parallel
    retval = pool.starmap(_run_helper, new_args)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/florin/anaconda3/envs/opence/conda-bld/work'`
```

Any advice?
Rgds,
FM

**Comment by npanpaliya** [comment]
@ticlazau - This is a known bug with conda-build 3.21.8. Please install conda-build 3.21.7 version to get rid of this issue.

**Comment by ticlazau** [comment]
@npanpaliya thank you!
